name: Dependabot Pull Request

on:
  pull_request_target:
    branches:
      - 'dependabot/**'

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto merge pull request
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.CI_GH_TOKEN }}
